// Eclusa Crestuma-Lever — geometric constants (scale ~1u = 1m)
export const FLOOR_Y = -8.0
export const LOW_Y   = -6.5
export const HIGH_Y  =  2.0
export const WALL_H  = 14.0
export const WALL_TOP = FLOOR_Y + WALL_H   // 6.0
export const CW      = 6.5
export const CL      = 26.0
export const WT      = 1.6
export const Z_JUS   = CL / 2             // 13
export const Z_MON   = -CL / 2            // -13
export const DESNIVEL_REAL = 14.0
export const COTA_JUS = 2.0
export const OA      = Math.PI / 2 * 0.96
export const GHj     = 10.5   // downstream gate height
export const GDj     = 0.85
export const GHv     = 11.0   // upstream gate height
export const GDv     = 0.72
export const VW      = CW + WT * 1.6
export const VAG_CY  = FLOOR_Y + GHv / 2 + 0.15
export const VAG_OY  = VAG_CY - GHv * 0.58
